package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'As_Af'
in the project with id = 'As', and delete the patch script.
*/
create(RelativeId("As"), BuildType({
    id("As_Af")
    name = "af"
}))

